name: Quantum CI
on: [push, pull_request]

jobs:
  test-collapsed-apps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
      - name: Detect Materialized Apps
        run: |
          for app in superposition/apps/*/package.json; do
            if [ -f "$app" ]; then
              app_name=$(dirname "$app" | xargs basename)
              pnpm install --filter @goddesse/$app_name
              pnpm test --filter @goddesse/$app_name
            fi
          done
